-- Show available keybinds
-- https://github.com/folke/which-key.nvim

vim.pack.add({ 'https://github.com/folke/which-key.nvim' })

require('which-key').setup({
    preset = 'modern',
    delay = 0,
    icon = { mappings = vim.g.nerd_fonts },
    keys = vim.g.nerd_fonts and {} or {
        Up = '<Up> ',
        Down = '<Down> ',
        Left = '<Left> ',
        Right = '<Right> ',
        C = '<C-…> ',
        M = '<M-…> ',
        D = '<D-…> ',
        S = '<S-…> ',
        CR = '<CR> ',
        Esc = '<Esc> ',
        ScrollWheelDown = '<ScrollWheelDown> ',
        ScrollWheelUp = '<ScrollWheelUp> ',
        NL = '<NL> ',
        BS = '<BS> ',
        Space = '<Space> ',
        Tab = '<Tab> ',
        F1 = '<F1>',
        F2 = '<F2>',
        F3 = '<F3>',
        F4 = '<F4>',
        F5 = '<F5>',
        F6 = '<F6>',
        F7 = '<F7>',
        F8 = '<F8>',
        F9 = '<F9>',
        F10 = '<F10>',
        F11 = '<F11>',
        F12 = '<F12>',
    },
    spec = {
        { '[', group = 'Prev' },
        { ']', group = 'Next' },
        { 'g', group = 'Goto' },
        { 'gr', group = 'LSP actions', mode = { 'n' } },
        { '<leader>b', group = 'Debug' },
        { '<leader>c', group = 'Code' },
        { '<leader>d', group = 'Diagnostics' },
        { '<leader>f', group = 'Find', mode = { 'n', 'v' } },
        { '<leader>g', group = 'Git hunk', mode = { 'n', 'v' } },
        { '<leader>t', group = 'Toggle features' },
    },
})
