-- Remember keymaps by displaying a popup with possible keybindings
-- https://github.com/folke/which-key.nvim

return {
  'folke/which-key.nvim',
  event = 'VeryLazy',
  opts = {
    delay = 0,
    icons = {
      mappings = vim.g.nerd_fonts,
    },
    keys = vim.g.nerd_fonts and {} or {
      Up = '<Up> ',
      Down = '<Down> ',
      Left = '<Left> ',
      Right = '<Right> ',
      C = '<C-…> ',
      M = '<M-…> ',
      D = '<D-…> ',
      S = '<S-…> ',
      CR = '<CR> ',
      Esc = '<Esc> ',
      ScrollWheelDown = '<ScrollWheelDown> ',
      ScrollWheelUp = '<ScrollWheelUp> ',
      NL = '<NL> ',
      BS = '<BS> ',
      Space = '<Space> ',
      Tab = '<Tab> ',
      F1 = '<F1>',
      F2 = '<F2>',
      F3 = '<F3>',
      F4 = '<F4>',
      F5 = '<F5>',
      F6 = '<F6>',
      F7 = '<F7>',
      F8 = '<F8>',
      F9 = '<F9>',
      F10 = '<F10>',
      F11 = '<F11>',
      F12 = '<F12>',
    },
    spec = {
      { '[', group = 'Prev' },
      { ']', group = 'Next' },
      { 'g', group = 'Goto' },
      { 's', group = 'Surround' },
      { '<leader>b', group = 'Debug' },
      { '<leader>c', group = 'Code' },
      { '<leader>f', group = 'Find' },
      { '<leader>g', group = 'Git hunk', mode = { 'n', 'v' } },
      { '<leader>t', group = 'Toggle features' },
      { '<leader>x', group = 'Todos' },
    },
  },
}
